update env and gh workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,81 +1,81 @@
-name: Deploy Site
+# Sample workflow for building and deploying an Eleventy site to GitHub Pages
+name: Deploy Eleventy site to Pages
 
 on:
-  # push:
-  #   branches: [ master ]
+  # Runs on pushes targeting the default branch
+  push:
+    branches: [master, migrate-to-11ty]
+
+  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
+# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
+permissions:
+  contents: read
+  pages: write
+  id-token: write
+
+# Allow one concurrent deployment
+concurrency:
+  group: "pages"
+  cancel-in-progress: true
+
 jobs:
-  set-deploy-type:
+  # Build job
+  build:
     runs-on: ubuntu-latest
-    outputs:
-      target: ${{ steps.set-output.outputs.target }}
     steps:
-      - uses: actions/checkout@v3
-
-      - name: get deployment target
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Detect package manager
+        id: detect-package-manager
         run: |
-          TARGET=$(cat DEPLOY_STRATEGY)
-          echo "TARGET=$TARGET" >> $GITHUB_ENV
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine packager manager"
+            exit 1
+          fi
+      - name: Setup Node
+        uses: actions/setup-node@v3
+        with:
+          node-version: "16"
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+      - name: Setup Pages
+        uses: actions/configure-pages@v2
+      - name: Restore cache
+        uses: actions/cache@v3
+        with:
+          path: |
+            .eleventy/cache
+          # Generate a new cache whenever packages or source files change.
+          key: ${{ runner.os }}-eleventy-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
+          # If source files changed but packages didn't, rebuild from a prior cache.
+          restore-keys: |
+            ${{ runner.os }}-eleventy-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
+      - name: Install dependencies
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+      - name: Build
+        run: ${{ steps.detect-package-manager.outputs.manager }} run build
+      - name: Upload artifact
+        uses: actions/upload-pages-artifact@v1
+        with:
+          path: ./_site
 
-      - name: check if target is valid
-        if: success() && !contains(fromJSON('["gh-pages", "firebase", "none"]'), env.TARGET)
-        run: echo 'Invalid Deployment Target' && exit 1
-
-      # gh actions doesn't support using the 'env' context on job level ifs for
-      # some reason smh. here we use outputs instead
-      - name: set output to deploy target
-        id: set-output
-        run: echo "::set-output name=target::${{ env.TARGET }}"
-
-  # not sure if anyone wants this but I'm putting this here for those that don't
-  # want to host their site. else the actions will show an annoying x whenever
-  # you push to master
-  deploy-none:
+  # Deployment job
+  deploy:
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
     runs-on: ubuntu-latest
-    needs: set-deploy-type
-    if: needs.set-deploy-type.outputs.target == 'none'
+    needs: build
     steps:
-      - run: echo 'No Deployment Specified' && exit 0
-
-  deploy-gh-pages:
-    runs-on: ubuntu-latest
-    needs: set-deploy-type
-    if: needs.set-deploy-type.outputs.target == 'gh-pages'
-
-    steps:
-    - uses: actions/checkout@v3
-
-    - name: Deploy Jekyll Site
-      uses: sujaykundu777/jekyll-deploy-action@1.0.3
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
-        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
-
-  deploy-firebase:
-    runs-on: ubuntu-latest
-    needs: set-deploy-type
-    if: needs.set-deploy-type.outputs.target == 'firebase'
-
-    steps:
-    - uses: actions/checkout@v3
-
-    - name: setup ruby
-      uses: ruby/setup-ruby@v1
-      with:
-        bundler-cache: true
-
-    - name: build jekyll
-      run: |
-        bundler update
-        bundle install
-        bundle exec jekyll build
-
-    - name: deploy to firebase
-      uses: w9jds/firebase-action@master
-      with:
-        args: deploy --only hosting
-      env:
-        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
-        PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: actions/deploy-pages@v1
